### ISSUE TITLE
News page

### ISSUE THREAD

**Issue by SmruthyJoseph** [SmruthyJoseph/WordpressAssignment-1#11]
News page created.

**Comment by AbhijithHaridas** [comment]
@SmruthyJoseph are you working on this?

**Comment by SmruthyJoseph** [comment]
No, I have completed.

**Comment by AbhijithHaridas** [comment]
then why there is no status update on this issue?

**Comment by SmruthyJoseph** [comment]
I didn't commited properly so I am reverting this commit.

> then why there is no status update on this issue?
